"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { useLanguage } from "@/contexts/LanguageContext";
import * as storage from "@/utils/storage";
import LanguageToggle from "@/components/LanguageToggle";

interface ImageComposerProps {
  composedImage: string;
  onReset: () => void;
  user?: any;
  credits?: number | null;
  onSignOut?: (e?: React.MouseEvent) => void;
}

interface AnalysisData {
  avatar?: {
    description?: string;
    gender?: string;
    age?: string;
    pose?: string;
    clothing?: string;
  };
  product?: {
    name?: string;
    type?: string;
    brand?: string;
    color?: string;
    description?: string;
  };
  suggestion?: {
    placement?: string;
    interaction?: string;
    style?: string;
  };
}

interface CompositionData {
  avatar: string;
  product: string;
  analysis?: AnalysisData;
  customPrompt?: string | null;
  composition: {
    productScale: number;
    productX: number;
    productY: number;
    productRotation: number;
    explanation?: string;
  };
}

export default function ImageComposer({
  composedImage,
  onReset,
  user,
  credits,
  onSignOut,
}: ImageComposerProps) {
  const { t } = useLanguage();
  const router = useRouter();
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isComposing, setIsComposing] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImages, setGeneratedImages] = useState<string[]>([]);
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [originalCanvasData, setOriginalCanvasData] = useState<string | null>(null);
  const [originalAvatarImage, setOriginalAvatarImage] = useState<string | null>(null);
  const [originalProductImage, setOriginalProductImage] = useState<string | null>(null);
  const [referenceImages, setReferenceImages] = useState<string[]>([]);
  const [analysisData, setAnalysisData] = useState<AnalysisData | null>(null);
  const [userCustomPrompt, setUserCustomPrompt] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem("banana_has_auto_generated") === 'true';
    }
    return false;
  });

  // UI State
  const [isStylesOpen, setIsStylesOpen] = useState(true);
  const [isStudioOpen, setIsStudioOpen] = useState(true);
  const [studioHeight, setStudioHeight] = useState(45); // percentage of viewport height
  const [isResizing, setIsResizing] = useState(false);
  const [isPromptOpen, setIsPromptOpen] = useState(false);

  // Interactive State
  const [scale, setScale] = useState(1);
  const [rotation, setRotation] = useState(0);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [prompt, setPrompt] = useState(
    "Create a professional advertisement. Position the product naturally based on its type - hold if handheld, wear if wearable, or interact appropriately with larger items."
  );
  const [selectedPreset, setSelectedPreset] = useState("professional");

  // Load persisted data on mount
  useEffect(() => {
    const loadData = async () => {
      const [images, canvas] = await Promise.all([
        storage.getItem<string[]>("banana_generated_images"),
        storage.getItem<string>("banana_original_canvas_data")
      ]);
      if (images) setGeneratedImages(images);
      if (canvas) setOriginalCanvasData(canvas);
    };
    loadData();
  }, []);

  // Persist state changes
  useEffect(() => {
    if (generatedImages.length > 0) {
      storage.setItem("banana_generated_images", generatedImages);
    }
  }, [generatedImages]);

  useEffect(() => {
    localStorage.setItem("banana_has_auto_generated", String(hasAutoGenerated));
  }, [hasAutoGenerated]);

  useEffect(() => {
    if (originalCanvasData) {
      storage.setItem("banana_original_canvas_data", originalCanvasData);
    }
  }, [originalCanvasData]);

  // Preset prompts
  const presets = [
    {
      id: "professional",
      label: "💼 Professional",
      prompt: "Create a professional advertisement. Position the product naturally based on its type - hold if handheld, wear if wearable, or interact appropriately with larger items."
    },
    {
      id: "lifestyle",
      label: "🌟 Lifestyle",
      prompt: "Create a lifestyle advertisement showing natural daily use of the product. Make it relatable and aspirational."
    },
    {
      id: "vibrant",
      label: "🌈 Vibrant",
      prompt: "Vibrant and energetic ad with bold colors, perfect for social media. Product should be prominently featured."
    },
    {
      id: "minimal",
      label: "✨ Minimal",
      prompt: "Clean minimal aesthetic with soft lighting. Focus on the product with elegant simplicity."
    },
    {
      id: "outdoor",
      label: "🏖️ Outdoor",
      prompt: "Outdoor setting advertisement - beach, park, or nature. Natural lighting with lifestyle feel."
    },
    {
      id: "studio",
      label: "📸 Studio",
      prompt: "Professional studio advertisement with controlled lighting. Clean background, commercial quality."
    },
    {
      id: "luxury",
      label: "💎 Luxury",
      prompt: "High-end luxury advertisement with elegant golden lighting, premium feel. Sophisticated and exclusive atmosphere."
    },
    {
      id: "neon",
      label: "🌃 Neon City",
      prompt: "Cyberpunk neon city vibes with glowing lights, purple and blue tones. Urban night scene, futuristic."
    },
    {
      id: "retro",
      label: "📻 Retro",
      prompt: "Vintage retro style advertisement with warm film grain, 80s/90s nostalgic aesthetic. Classic advertising look."
    },
    {
      id: "anime",
      label: "🎌 Anime",
      prompt: "Anime-inspired art style advertisement. Vibrant colors, dramatic lighting, Japanese animation aesthetic."
    },
    {
      id: "fashion",
      label: "👗 Fashion",
      prompt: "High fashion editorial style. Dramatic poses, striking lighting, magazine cover quality."
    },
    {
      id: "wearing",
      label: "👕 Wear It",
      prompt: "Make the person WEAR the clothing/apparel product. The clothing item should be worn on the person's body naturally - shirt on torso, pants on legs, hat on head, glasses on face, watch on wrist, etc. Show the clothing being worn, not held. Professional fashion photography style."
    },
    {
      id: "cozy",
      label: "☕ Cozy",
      prompt: "Warm cozy atmosphere with soft warm lighting. Comfortable homey feel, inviting and relaxing."
    },
    {
      id: "sport",
      label: "⚡ Dynamic",
      prompt: "Dynamic action shot with motion blur effects. Energetic, powerful, athletic feel."
    },
    {
      id: "dreamy",
      label: "🌸 Dreamy",
      prompt: "Soft dreamy aesthetic with pastel colors, ethereal lighting. Romantic and whimsical atmosphere."
    },
    {
      id: "bold",
      label: "🔥 Bold",
      prompt: "Bold and dramatic with high contrast, striking shadows. Make a strong visual statement."
    },
    {
      id: "nature",
      label: "🌿 Natural",
      prompt: "Organic natural setting with plants and greenery. Eco-friendly, sustainable, fresh feel."
    }
  ];

  const handlePresetClick = (preset: typeof presets[0]) => {
    setPrompt(preset.prompt);
    setSelectedPreset(preset.id);
  };

  const handleReferenceUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;

    Array.from(files).forEach(file => {
      const reader = new FileReader();
      reader.onload = (event) => {
        const result = event.target?.result as string;
        setReferenceImages(prev => [...prev, result]);
      };
      reader.readAsDataURL(file);
    });
    e.target.value = ''; // Reset input
  };

  const removeReferenceImage = (index: number) => {
    setReferenceImages(prev => prev.filter((_, i) => i !== index));
  };

  // Image Refs
  const avatarImgRef = useRef<HTMLImageElement | null>(null);
  const productImgRef = useRef<HTMLImageElement | null>(null);

  // Initialize from props
  useEffect(() => {
    const init = async () => {
      try {
        const data: CompositionData = JSON.parse(composedImage);

        // Load images
        const avatarImg = new Image();
        const productImg = new Image();
        avatarImg.crossOrigin = "anonymous";
        productImg.crossOrigin = "anonymous";

        await Promise.all([
          new Promise<void>((resolve, reject) => {
            avatarImg.onload = () => resolve();
            avatarImg.onerror = () => reject(new Error("Failed to load avatar"));
            avatarImg.src = data.avatar;
          }),
          new Promise<void>((resolve, reject) => {
            productImg.onload = () => resolve();
            productImg.onerror = () => reject(new Error("Failed to load product"));
            productImg.src = data.product;
          })
        ]);

        avatarImgRef.current = avatarImg;
        productImgRef.current = productImg;

        // Store original images for regeneration
        setOriginalAvatarImage(data.avatar);
        setOriginalProductImage(data.product);

        // Store analysis data if available
        if (data.analysis) {
          setAnalysisData(data.analysis);
        }

        // Store custom prompt if available
        if (data.customPrompt) {
          setUserCustomPrompt(data.customPrompt);
        }

        // Set initial state from AI suggestion
        setScale(data.composition.productScale);
        setRotation(data.composition.productRotation);
        setPosition({ x: data.composition.productX, y: data.composition.productY });

        setIsComposing(false);
        // Force redraw after images are loaded with the correct values
        setTimeout(() => {
          if (canvasRef.current && avatarImgRef.current && productImgRef.current) {
            const canvas = canvasRef.current;
            const ctx = canvas.getContext('2d');
            if (!ctx) return;

            // Set canvas dimensions to match avatar
            canvas.width = avatarImgRef.current.width;
            canvas.height = avatarImgRef.current.height;

            // Clear canvas
            ctx.clearRect(0, 0, canvas.width, canvas.height);

            // Draw avatar (background)
            ctx.drawImage(avatarImgRef.current, 0, 0);

            // Draw product (foreground) with transformations using data values
            ctx.save();
            ctx.translate(data.composition.productX, data.composition.productY);
            ctx.rotate((data.composition.productRotation * Math.PI) / 180);
            const productWidth = productImgRef.current.width * data.composition.productScale;
            const productHeight = productImgRef.current.height * data.composition.productScale;
            ctx.drawImage(
              productImgRef.current,
              -productWidth / 2,
              -productHeight / 2,
              productWidth,
              productHeight
            );
            ctx.restore();
          }
        }, 100);
      } catch (error) {
        console.error("Failed to init composer:", error);
        setIsComposing(false);
      }
    };
    init();
  }, [composedImage]);

  // Draw Canvas
  const drawCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    const avatarImg = avatarImgRef.current;
    const productImg = productImgRef.current;

    if (!canvas || !avatarImg || !productImg) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Set dimensions
    canvas.width = avatarImg.width;
    canvas.height = avatarImg.height;

    // Clear
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Draw Avatar
    ctx.drawImage(avatarImg, 0, 0);

    // Draw Product with transforms
    ctx.save();
    const productWidth = productImg.width * scale;
    const productHeight = productImg.height * scale;

    ctx.translate(position.x, position.y);
    ctx.rotate((rotation * Math.PI) / 180);
    ctx.drawImage(
      productImg,
      -productWidth / 2,
      -productHeight / 2,
      productWidth,
      productHeight
    );
    ctx.restore();
  }, [scale, rotation, position]);

  // Redraw when state changes
  useEffect(() => {
    if (!isComposing) {
      drawCanvas();
    }
  }, [drawCanvas, isComposing]);

  // Event Handlers
  const handleMouseDown = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (generatedImages.length > 0) return;
    const rect = canvasRef.current?.getBoundingClientRect();
    if (!rect) return;

    // Calculate mouse position relative to canvas scale (if displayed size != actual size)
    const scaleX = canvasRef.current!.width / rect.width;
    const scaleY = canvasRef.current!.height / rect.height;

    setIsDragging(true);
    setDragStart({
      x: (e.clientX - rect.left) * scaleX - position.x,
      y: (e.clientY - rect.top) * scaleY - position.y
    });
  };

  const handleMouseMove = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!isDragging || generatedImages.length > 0) return;
    const rect = canvasRef.current?.getBoundingClientRect();
    if (!rect) return;

    const scaleX = canvasRef.current!.width / rect.width;
    const scaleY = canvasRef.current!.height / rect.height;

    setPosition({
      x: (e.clientX - rect.left) * scaleX - dragStart.x,
      y: (e.clientY - rect.top) * scaleY - dragStart.y
    });
  };

  const handleMouseUp = () => setIsDragging(false);
  const handleMouseLeave = () => setIsDragging(false);

  const handleWheel = (e: React.WheelEvent<HTMLCanvasElement>) => {
    if (generatedImages.length > 0) return;
    e.preventDefault();
    const delta = e.deltaY * -0.001;
    const newScale = Math.min(Math.max(0.1, scale + delta), 5);
    setScale(newScale);
  };

  const handleGenerateAI = async () => {
    console.log('handleGenerateAI called, isGenerating:', isGenerating);

    // We need both original images for regeneration
    if (!originalAvatarImage || !originalProductImage) {
      console.error('No original images available');
      return;
    }

    setIsGenerating(true);
    try {
      // Build enhanced prompt with analysis data
      let enhancedPrompt = prompt;
      if (analysisData?.product) {
        const productInfo = [];
        if (analysisData.product.name) productInfo.push(`Product: ${analysisData.product.name}`);
        if (analysisData.product.brand) productInfo.push(`Brand: ${analysisData.product.brand}`);
        if (analysisData.product.type) productInfo.push(`Type: ${analysisData.product.type}`);
        if (productInfo.length > 0) {
          enhancedPrompt = `${productInfo.join(', ')}. ${prompt}`;
        }
      }
      if (analysisData?.suggestion) {
        if (analysisData.suggestion.placement) {
          enhancedPrompt += ` Place the product ${analysisData.suggestion.placement}.`;
        }
        if (analysisData.suggestion.interaction) {
          enhancedPrompt += ` The model should be ${analysisData.suggestion.interaction}.`;
        }
      }
      // Add user's custom prompt if provided
      if (userCustomPrompt) {
        enhancedPrompt += ` Additional instructions: ${userCustomPrompt}`;
      }

      console.log('Sending request to /api/compose with 2 images and prompt:', enhancedPrompt, 'refs:', referenceImages.length);
      const response = await fetch("/api/compose", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          avatarImage: originalAvatarImage,
          productImage: originalProductImage,
          prompt: enhancedPrompt,
          referenceImages: referenceImages,
        }),
      });

      const data = await response.json();
      console.log('Received response:', data);
      if (data.generatedImage) {
        console.log('Adding new image to array, current count:', generatedImages.length);
        setGeneratedImages(prev => {
          const newArray = [...prev, data.generatedImage];
          console.log('New array length:', newArray.length);
          // Set index to the last item (new image)
          setCurrentImageIndex(newArray.length - 1);
          return newArray;
        });
        console.log('Image added successfully');
      } else if (data.error) {
        console.error("API error:", data.error);
      }
    } catch (error) {
      console.error("Error generating AI image:", error);
    } finally {
      setIsGenerating(false);
      console.log('Generation complete');
    }
  };

  // Auto-generate on first load
  useEffect(() => {
    if (!isComposing && !hasAutoGenerated && originalAvatarImage && originalProductImage) {
      const timer = setTimeout(() => {
        handleGenerateAI();
        setHasAutoGenerated(true);
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [isComposing, hasAutoGenerated, originalAvatarImage, originalProductImage]);

  const handleRegenerate = async () => {
    // Trigger AI generation with the new prompt/style
    await handleGenerateAI();
  };

  // Studio height drag handlers
  const handleResizeStart = (e: React.TouchEvent | React.MouseEvent) => {
    setIsResizing(true);
    e.preventDefault();
  };

  useEffect(() => {
    if (!isResizing) return;

    const handleMove = (e: TouchEvent | MouseEvent) => {
      const clientY = 'touches' in e ? e.touches[0].clientY : e.clientY;
      const windowHeight = window.innerHeight;
      const newHeight = ((windowHeight - clientY) / windowHeight) * 100;
      setStudioHeight(Math.min(Math.max(newHeight, 10), 80)); // Clamp between 10% and 80%
    };

    const handleEnd = () => {
      setIsResizing(false);
    };

    window.addEventListener('touchmove', handleMove);
    window.addEventListener('mousemove', handleMove);
    window.addEventListener('touchend', handleEnd);
    window.addEventListener('mouseup', handleEnd);

    return () => {
      window.removeEventListener('touchmove', handleMove);
      window.removeEventListener('mousemove', handleMove);
      window.removeEventListener('touchend', handleEnd);
      window.removeEventListener('mouseup', handleEnd);
    };
  }, [isResizing]);

  const handleDownload = async () => {
    const imageToDownload = generatedImages[currentImageIndex] || canvasRef.current?.toDataURL("image/png");
    if (!imageToDownload) return;

    // Extract mime type and extension
    const mimeMatch = imageToDownload.match(/^data:([^;]+);/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/png';
    const extension = mimeType.split('/')[1] || 'png';
    const filename = `banana-composed-${Date.now()}.${extension}`;

    try {
      // Convert data URL to blob
      const response = await fetch(imageToDownload);
      const blob = await response.blob();

      // Try File System Access API first (shows native Save As dialog)
      if ('showSaveFilePicker' in window) {
        try {
          const handle = await (window as any).showSaveFilePicker({
            suggestedName: filename,
            types: [{
              description: 'Image',
              accept: { [mimeType]: [`.${extension}`] },
            }],
          });
          const writable = await handle.createWritable();
          await writable.write(blob);
          await writable.close();
          return; // Success!
        } catch (err: any) {
          // User cancelled - that's ok, just return
          if (err.name === 'AbortError') return;
          // Otherwise fall through to legacy method
          console.log('showSaveFilePicker failed, trying fallback:', err);
        }
      }

      // Fallback: blob URL download
      const blobUrl = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = blobUrl;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setTimeout(() => URL.revokeObjectURL(blobUrl), 1000);
    } catch (error) {
      console.error('Download failed:', error);
      window.open(imageToDownload, '_blank');
    }
  };

  const handleCreateVideo = async () => {
    if (generatedImages.length > 0) {
      const image = generatedImages[currentImageIndex];
      await storage.setItem("banana_video_source", image);
      router.push("/video");
    }
  };

  return (
    <div className="h-screen w-full flex flex-col lg:flex-row overflow-hidden relative">
      {/* Header Controls - Fixed positioning with proper mobile spacing */}
      <div className="absolute top-2 lg:top-4 left-2 lg:left-4 right-2 lg:right-auto z-50 flex items-center gap-2 lg:gap-4">
        {user && (
          <div className="flex items-center gap-2 lg:gap-3 bg-white px-2 lg:px-3 py-1 lg:py-1.5 rounded-full border-2 border-black shadow-hard z-[100] text-xs lg:text-sm">
            <span className="font-bold whitespace-nowrap">🍌 {credits}</span>
            <button
              onClick={() => router.push("/features")}
              className="bg-gradient-to-r from-yellow-100 to-orange-100 hover:from-yellow-200 hover:to-orange-200 text-orange-600 px-1.5 lg:px-2 py-0.5 lg:py-1 rounded-md text-[10px] lg:text-xs font-black border-2 border-transparent hover:border-orange-300 transition-all uppercase tracking-wider"
            >
              Features
            </button>
            <button
              onClick={() => router.push("/model-pose")}
              className="bg-pink-100 hover:bg-pink-200 text-pink-600 px-1.5 lg:px-2 py-0.5 lg:py-1 rounded-md text-[10px] lg:text-xs font-black border-2 border-transparent hover:border-pink-300 transition-all uppercase tracking-wider hidden lg:block"
            >
              Pose
            </button>
            <button
              onClick={() => router.push("/asset")}
              className="bg-purple-100 hover:bg-purple-200 text-purple-600 px-1.5 lg:px-2 py-0.5 lg:py-1 rounded-md text-[10px] lg:text-xs font-black border-2 border-transparent hover:border-purple-300 transition-all uppercase tracking-wider hidden lg:block"
            >
              Assets
            </button>
            {onSignOut && (
              <button
                onClick={onSignOut}
                className="bg-gray-100 hover:bg-red-100 text-gray-600 hover:text-red-600 px-1.5 lg:px-2 py-0.5 lg:py-1 rounded-md text-[10px] lg:text-xs font-black border-2 border-transparent hover:border-red-200 transition-all uppercase tracking-wider"
              >
                Out
              </button>
            )}
          </div>
        )}
        <LanguageToggle />
      </div>

      {/* Canvas Area - Add top padding on mobile to avoid header overlap */}
      <div className="flex-1 relative flex flex-col items-center justify-center overflow-hidden pt-14 lg:pt-0 p-2 sm:p-4 lg:p-0">
        {/* Decorative Background */}
        <div className="absolute inset-0 opacity-10 pointer-events-none hidden lg:block">
          <div className="absolute top-10 left-10 text-9xl rotate-12">🍌</div>
          <div className="absolute bottom-20 right-20 text-9xl -rotate-12">✨</div>
        </div>

        <div className="relative p-2 lg:p-4 bg-white border-2 lg:border-4 border-black shadow-hard lg:shadow-hard-lg lg:rotate-1 rounded-lg lg:rounded-xl max-w-[95%] lg:max-w-[90%] flex items-center justify-center">
          {/* Tape effect - desktop only */}
          <div className="hidden lg:block absolute -top-4 left-1/2 -translate-x-1/2 w-32 h-8 bg-yellow-200/80 rotate-1 shadow-sm z-20"></div>

          <div className="relative overflow-hidden border lg:border-2 border-black rounded-lg bg-gray-50">
            {(isComposing || isGenerating) && (
              <div className="absolute inset-0 flex items-center justify-center bg-white/90 z-10 backdrop-blur-sm">
                <div className="text-center">
                  <div className="inline-block animate-spin text-6xl mb-4">🍌</div>
                  <p className="text-2xl font-black text-black">
                    {isComposing ? "LOADING..." : "MAGIC HAPPENING..."}
                  </p>
                </div>
              </div>
            )}

            {(() => {
              console.log('Render check - generatedImages.length:', generatedImages.length, 'currentImageIndex:', currentImageIndex);
              if (generatedImages.length > 0) {
                console.log('Showing image at index:', currentImageIndex, 'URL:', generatedImages[currentImageIndex]?.substring(0, 50));
              }
              return null;
            })()}

            {generatedImages.length > 0 ? (
              <div className="relative">
                <img
                  src={generatedImages[currentImageIndex]}
                  alt="AI Generated"
                  className="max-w-full max-h-[40vh] sm:max-h-[60vh] lg:max-h-[80vh] object-contain"
                />
                {/* Use as Reference button */}
                <button
                  onClick={() => {
                    const currentImage = generatedImages[currentImageIndex];
                    if (currentImage && referenceImages.length < 3 && !referenceImages.includes(currentImage)) {
                      setReferenceImages(prev => [...prev, currentImage]);
                    }
                  }}
                  disabled={referenceImages.length >= 3 || referenceImages.includes(generatedImages[currentImageIndex])}
                  className="absolute bottom-2 right-2 bg-purple-600 hover:bg-purple-700 text-white px-3 py-1.5 rounded-lg text-xs font-bold shadow-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1"
                  title="Use this image as output reference for next generation"
                >
                  🎯 Use as Ref
                </button>
              </div>
            ) : (
              <canvas
                ref={canvasRef}
                onMouseDown={handleMouseDown}
                onMouseMove={handleMouseMove}
                onMouseUp={handleMouseUp}
                onMouseLeave={handleMouseLeave}
                onWheel={handleWheel}
                className="max-w-full max-h-[80vh] cursor-move touch-manipulation"
                style={{ touchAction: 'none' }}
              />
            )}
          </div>

          {/* Carousel Navigation - Desktop only (inside frame) */}
          {generatedImages.length > 1 && (
            <div className="hidden sm:block mt-3 sm:mt-4 space-y-2 sm:space-y-3">
              {/* Navigation Buttons */}
              <div className="flex items-center justify-center gap-2 sm:gap-4">
                <button
                  onClick={() => setCurrentImageIndex(Math.max(0, currentImageIndex - 1))}
                  disabled={currentImageIndex === 0}
                  className="btn-pop bg-white border-2 border-black px-3 sm:px-4 py-2 sm:py-2.5 rounded-lg font-bold text-sm sm:text-base disabled:opacity-30 disabled:cursor-not-allowed hover:bg-banana transition-colors min-w-[70px] sm:min-w-[80px]"
                >
                  ← PREV
                </button>
                <span className="font-black text-base sm:text-lg px-2">
                  {currentImageIndex + 1} / {generatedImages.length}
                </span>
                <button
                  onClick={() => setCurrentImageIndex(Math.min(generatedImages.length - 1, currentImageIndex + 1))}
                  disabled={currentImageIndex === generatedImages.length - 1}
                  className="btn-pop bg-white border-2 border-black px-3 sm:px-4 py-2 sm:py-2.5 rounded-lg font-bold text-sm sm:text-base disabled:opacity-30 disabled:cursor-not-allowed hover:bg-banana transition-colors min-w-[70px] sm:min-w-[80px]"
                >
                  NEXT →
                </button>
              </div>


              {/* Thumbnail Gallery */}
              <div className="grid grid-cols-3 gap-1 sm:gap-1.5 px-1 sm:px-2 max-w-[280px] sm:max-w-xs mx-auto">
                {generatedImages.map((img, index) => (
                  <button
                    key={index}
                    onClick={() => setCurrentImageIndex(index)}
                    className={`
                      border-2 sm:border-3 rounded-md overflow-hidden transition-all aspect-square
                      ${index === currentImageIndex
                        ? 'border-banana scale-105 shadow-hard'
                        : 'border-gray-300 hover:border-black opacity-70 hover:opacity-100'
                      }
                    `}
                  >
                    <img
                      src={img}
                      alt={`Generated ${index + 1}`}
                      className="w-full h-full object-cover"
                    />
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Carousel Navigation - Mobile only (below frame) */}
        {generatedImages.length > 1 && (
          <div className="sm:hidden mt-4 space-y-3 w-full max-w-md">
            {/* Navigation Buttons */}
            <div className="flex items-center justify-center gap-2">
              <button
                onClick={() => setCurrentImageIndex(Math.max(0, currentImageIndex - 1))}
                disabled={currentImageIndex === 0}
                className="btn-pop bg-white border-2 border-black px-3 py-2 rounded-lg font-bold text-sm disabled:opacity-30 disabled:cursor-not-allowed hover:bg-banana transition-colors min-w-[70px]"
              >
                ← PREV
              </button>
              <span className="font-black text-base px-2">
                {currentImageIndex + 1} / {generatedImages.length}
              </span>
              <button
                onClick={() => setCurrentImageIndex(Math.min(generatedImages.length - 1, currentImageIndex + 1))}
                disabled={currentImageIndex === generatedImages.length - 1}
                className="btn-pop bg-white border-2 border-black px-3 py-2 rounded-lg font-bold text-sm disabled:opacity-30 disabled:cursor-not-allowed hover:bg-banana transition-colors min-w-[70px]"
              >
                NEXT →
              </button>
            </div>


            {/* Thumbnail Gallery */}
            <div className="grid grid-cols-3 gap-1 px-1 max-w-[280px] mx-auto">
              {generatedImages.map((img, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentImageIndex(index)}
                  className={`
                    border-2 rounded-md overflow-hidden transition-all aspect-square
                    ${index === currentImageIndex
                      ? 'border-banana scale-105 shadow-hard'
                      : 'border-gray-300 hover:border-black opacity-70 hover:opacity-100'
                    }
                  `}
                >
                  <img
                    src={img}
                    alt={`Generated ${index + 1}`}
                    className="w-full h-full object-cover"
                  />
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Mobile Open Button - Shows when studio is closed */}
      {!isStudioOpen && (
        <button
          onClick={() => setIsStudioOpen(true)}
          className="lg:hidden fixed bottom-4 right-4 z-30 bg-pop-blue text-white px-4 py-3 rounded-full border-2 border-black shadow-hard flex items-center gap-2 font-bold"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
          </svg>
          Studio
        </button>
      )}

      {/* Sidebar Controls - Simplified on mobile */}
      <div
        className={`studio-sidebar w-full lg:w-96 bg-white border-t-2 lg:border-t-4 lg:border-l-4 border-black shadow-lg lg:shadow-xl flex flex-col lg:h-full z-20 transition-all ${isResizing ? '' : 'duration-300'} ${isStudioOpen ? '' : 'max-h-0 lg:max-h-full overflow-hidden lg:overflow-visible border-t-0 lg:border-t-4'}`}
        style={{ maxHeight: isStudioOpen ? `${studioHeight}vh` : undefined }}
      >
        {/* Drag Handle - Mobile only */}
        <div
          className="lg:hidden flex items-center justify-center py-2 cursor-ns-resize touch-none bg-gray-100 border-b border-gray-300"
          onTouchStart={handleResizeStart}
          onMouseDown={handleResizeStart}
        >
          <div className="w-12 h-1.5 bg-gray-400 rounded-full"></div>
        </div>

        <div className="p-2 sm:p-3 lg:p-6 border-b-2 lg:border-b-4 border-black bg-pop-blue text-white flex items-center justify-between">
          <div>
            <h2 className="text-base sm:text-lg lg:text-2xl font-black text-outline">{t.studio}</h2>
            <p className="text-[10px] sm:text-xs font-bold opacity-90">{t.step2}</p>
          </div>
          <button
            onClick={() => setIsStudioOpen(!isStudioOpen)}
            className="lg:hidden p-2 hover:bg-white/20 rounded-lg transition-colors"
          >
            {isStudioOpen ? (
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            ) : (
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
              </svg>
            )}
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-2 sm:p-3 lg:p-6 space-y-2 sm:space-y-3 lg:space-y-8">
          {generatedImages.length === 0 && !hasAutoGenerated ? (
            <>
              {/* Instructions */}
              <div className="bg-yellow-50 p-3 sm:p-4 rounded-xl border-2 border-yellow-400 text-xs sm:text-sm font-bold text-yellow-800">
                💡 {t.tipDrag}
              </div>

              {/* Sliders */}
              <div className="space-y-4 sm:space-y-6">
                <div>
                  <label className="block text-base sm:text-lg font-black text-black mb-2">
                    {t.scale}: {Math.round(scale * 100)}%
                  </label>
                  <input
                    type="range"
                    min="0.1"
                    max="3"
                    step="0.1"
                    value={scale}
                    onChange={(e) => setScale(parseFloat(e.target.value))}
                    className="w-full h-6 sm:h-4 bg-black rounded-full appearance-none cursor-pointer accent-banana border-2 border-white touch-manipulation"
                  />
                </div>
                <div>
                  <label className="block text-base sm:text-lg font-black text-black mb-2">
                    {t.rotation}: {Math.round(rotation)}°
                  </label>
                  <input
                    type="range"
                    min="-180"
                    max="180"
                    value={rotation}
                    onChange={(e) => setRotation(parseInt(e.target.value))}
                    className="w-full h-6 sm:h-4 bg-black rounded-full appearance-none cursor-pointer accent-banana border-2 border-white touch-manipulation"
                  />
                </div>
              </div>

              {/* Detected Product Info */}
              {analysisData?.product?.name && (
                <div className="mb-4 p-3 bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-300 rounded-xl">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-lg">📦</span>
                    <span className="font-black text-green-700 text-sm">Detected Product</span>
                  </div>
                  <p className="font-bold text-green-900">
                    {analysisData.product.name}
                    {analysisData.product.brand && ` (${analysisData.product.brand})`}
                  </p>
                  {analysisData.product.type && (
                    <span className="inline-block mt-1 px-2 py-0.5 bg-green-200 rounded text-xs font-bold text-green-800">
                      {analysisData.product.type}
                    </span>
                  )}
                </div>
              )}

              {/* Prompt Presets */}
              <div>
                <label className="block text-base sm:text-lg font-black text-black mb-2">
                  {t.quickStyles}
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-1.5 sm:gap-2 mb-3 max-h-[180px] overflow-y-auto pr-1">
                  {presets.map((preset) => (
                    <button
                      key={preset.id}
                      onClick={() => handlePresetClick(preset)}
                      className={`
                        px-2 py-1.5 sm:px-3 sm:py-2 rounded-lg font-bold text-[10px] sm:text-xs border-2 transition-all whitespace-nowrap
                        ${selectedPreset === preset.id
                          ? 'bg-banana border-black text-black shadow-hard'
                          : 'bg-white border-gray-300 text-gray-700 hover:border-black'
                        }
                      `}
                    >
                      {preset.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Prompt */}
              <div>
                <label className="block text-base sm:text-lg font-black text-black mb-2">
                  {t.aiPrompt}
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder={t.promptPlaceholder}
                  className="w-full bg-white border-bold rounded-lg p-3 text-black placeholder-gray-400 focus:ring-4 focus:ring-banana focus:outline-none resize-y h-64 sm:h-80 text-sm sm:text-lg font-medium shadow-inner touch-manipulation"
                />
              </div>
            </>
          ) : (
            <>


              {/* Allow changing prompt after generation */}
              <div className="space-y-4 sm:space-y-6">
                {/* Prompt Presets */}
                {/* Prompt Presets */}
                <div className="border-2 border-gray-200 rounded-xl p-3 bg-white">
                  <div
                    className="flex items-center justify-between cursor-pointer select-none"
                    onClick={() => setIsStylesOpen(!isStylesOpen)}
                  >
                    <label className="block text-sm sm:text-base font-black text-black cursor-pointer m-0 flex-1 mr-2">
                      {t.tryDifferentStyle}
                    </label>
                    <span className="text-lg font-bold text-gray-500 flex-shrink-0">{isStylesOpen ? '−' : '+'}</span>
                  </div>

                  {isStylesOpen && (
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-1.5 sm:gap-2 mt-3 pr-1">
                      {presets.map((preset) => (
                        <button
                          key={preset.id}
                          onClick={() => handlePresetClick(preset)}
                          className={`
                            px-2 py-1.5 sm:px-3 sm:py-2 rounded-lg font-bold text-[10px] sm:text-xs border-2 transition-all flex items-center justify-center gap-1 text-center leading-tight
                            ${selectedPreset === preset.id
                              ? 'bg-banana border-black text-black shadow-hard'
                              : 'bg-white border-gray-300 text-gray-700 hover:border-black'
                            }
                          `}
                        >
                          {preset.label}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {/* Prompt */}
                {/* Prompt */}
                <div className="border-2 border-gray-200 rounded-xl p-3 bg-white">
                  <div
                    className="flex items-center justify-between cursor-pointer select-none"
                    onClick={() => setIsPromptOpen(!isPromptOpen)}
                  >
                    <label className="block text-sm sm:text-base font-black text-black cursor-pointer m-0 flex-1 mr-2">
                      {t.customPrompt}
                    </label>
                    <span className="text-lg font-bold text-gray-500 flex-shrink-0">{isPromptOpen ? '−' : '+'}</span>
                  </div>

                  {isPromptOpen && (
                    <div className="mt-3">
                      <textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder={t.promptPlaceholder}
                        className="w-full bg-gray-50 border-2 border-gray-200 rounded-lg p-3 text-black placeholder-gray-400 focus:ring-2 focus:ring-banana focus:border-black focus:outline-none resize-y h-64 sm:h-80 text-xs sm:text-sm font-medium touch-manipulation"
                      />
                    </div>
                  )}
                </div>

                {/* Reference Images */}
                <div className="border-2 border-purple-200 rounded-xl p-3 bg-purple-50">
                  <label className="block text-sm sm:text-base font-black text-purple-700 mb-2">
                    🎯 Output Reference (Optional)
                  </label>
                  <p className="text-xs text-purple-600 mb-3">
                    Add example images showing how you want the result to look (pose, style, composition)
                  </p>

                  {/* Reference Image Grid */}
                  <div className="grid grid-cols-3 gap-2 mb-3">
                    {referenceImages.map((img, index) => (
                      <div key={index} className="relative aspect-square bg-white rounded-lg overflow-hidden border-2 border-purple-300">
                        <img src={img} alt={`Ref ${index + 1}`} className="w-full h-full object-cover" />
                        <button
                          onClick={() => removeReferenceImage(index)}
                          className="absolute top-1 right-1 bg-red-500 text-white w-5 h-5 rounded-full text-xs font-bold hover:bg-red-600"
                        >
                          ✕
                        </button>
                      </div>
                    ))}

                    {/* Add Button */}
                    {referenceImages.length < 3 && (
                      <label className="aspect-square bg-white border-2 border-dashed border-purple-300 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-purple-500 hover:bg-purple-100 transition-colors">
                        <span className="text-2xl text-purple-400">+</span>
                        <span className="text-xs text-purple-500 font-bold">Add</span>
                        <input
                          type="file"
                          accept="image/*"
                          onChange={handleReferenceUpload}
                          className="hidden"
                        />
                      </label>
                    )}
                  </div>

                  {referenceImages.length > 0 && (
                    <button
                      onClick={() => setReferenceImages([])}
                      className="text-xs text-purple-600 hover:text-purple-800 font-bold"
                    >
                      Clear all references
                    </button>
                  )}
                </div>
              </div>
            </>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-2 sm:p-4 lg:p-6 border-t-2 lg:border-t-4 border-black bg-gray-50 space-y-2 sm:space-y-3">
          {generatedImages.length === 0 && !hasAutoGenerated ? (
            <>
              <button
                onClick={handleGenerateAI}
                disabled={isGenerating}
                className="w-full btn-pop bg-pop-pink text-white py-2 sm:py-3 rounded-xl flex items-center justify-center gap-2 disabled:opacity-50 text-xs sm:text-sm font-black touch-manipulation"
              >
                {isGenerating ? t.enhancing : `✨ ${t.enhanceWithAI} (1 🍌)`}
              </button>
              <button
                onClick={onReset}
                className="w-full py-1.5 sm:py-2 font-bold text-gray-500 hover:text-black transition-colors text-xs sm:text-sm touch-manipulation"
              >
                {t.startOver}
              </button>
            </>
          ) : (
            <>
              <button
                onClick={handleRegenerate}
                disabled={isGenerating}
                className="w-full btn-pop bg-pop-pink text-white py-2 sm:py-3 rounded-xl flex items-center justify-center gap-2 disabled:opacity-50 text-xs sm:text-sm font-black touch-manipulation"
              >
                {isGenerating ? (generatedImages.length === 0 ? t.enhancing : t.regenerating) : `🔄 ${t.regenerate} (1 🍌)`}
              </button>
              {generatedImages.length > 0 && (
                <button
                  onClick={handleDownload}
                  className="w-full btn-pop bg-pop-green text-white py-2 sm:py-3 rounded-xl flex items-center justify-center gap-2 text-xs sm:text-sm font-black touch-manipulation"
                >
                  {t.download} 💾
                </button>
              )}
              {generatedImages.length > 0 && (
                <button
                  onClick={handleCreateVideo}
                  className="w-full btn-pop bg-pop-purple text-white py-2 sm:py-3 rounded-xl flex items-center justify-center gap-2 text-xs sm:text-sm font-black touch-manipulation"
                >
                  Create Video 🎥
                </button>
              )}
              <button
                onClick={onReset}
                className="w-full py-1.5 sm:py-2 font-bold text-gray-500 hover:text-black transition-colors text-xs sm:text-sm touch-manipulation"
              >
                {t.createNew} 🍌
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
